import type { Client, Proposal, Contract } from "./types"

export const mockClients: Client[] = [
  {
    id: "1",
    name: "María González",
    email: "maria@techcorp.com",
    phone: "+34 612 345 678",
    company: "TechCorp Solutions",
    status: "active",
    industry: "Tecnología",
    assignedTo: "Juan Pérez",
    value: 45000,
    lastContact: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Cliente prioritario, interesado en soluciones cloud",
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    email: "carlos@innovatech.es",
    phone: "+34 623 456 789",
    company: "InnovaTech",
    status: "lead",
    industry: "Consultoría",
    assignedTo: "Ana López",
    value: 28000,
    lastContact: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Contacto inicial, pendiente de reunión",
  },
  {
    id: "3",
    name: "Laura Martínez",
    email: "laura@digitalplus.com",
    phone: "+34 634 567 890",
    company: "Digital Plus",
    status: "active",
    industry: "Marketing Digital",
    assignedTo: "Juan Pérez",
    value: 62000,
    lastContact: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Cliente recurrente, muy satisfecho con el servicio",
  },
  {
    id: "4",
    name: "Pedro Sánchez",
    email: "pedro@startuplab.io",
    phone: "+34 645 678 901",
    company: "StartupLab",
    status: "lead",
    industry: "Startups",
    assignedTo: "Ana López",
    value: 15000,
    lastContact: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    name: "Isabel Torres",
    email: "isabel@ecommercepro.es",
    phone: "+34 656 789 012",
    company: "EcommercePro",
    status: "active",
    industry: "E-commerce",
    assignedTo: "Juan Pérez",
    value: 38000,
    lastContact: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Interesado en expansión internacional",
  },
]

export const mockProposals: Proposal[] = [
  {
    id: "1",
    clientId: "1",
    title: "Implementación Cloud Infrastructure",
    description: "Migración completa a infraestructura cloud con AWS",
    value: 45000,
    status: "sent",
    priority: "high",
    validUntil: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    sentAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { id: "1", description: "Consultoría y análisis", quantity: 40, unitPrice: 150, total: 6000 },
      { id: "2", description: "Implementación AWS", quantity: 200, unitPrice: 120, total: 24000 },
      { id: "3", description: "Migración de datos", quantity: 80, unitPrice: 100, total: 8000 },
      { id: "4", description: "Capacitación equipo", quantity: 20, unitPrice: 200, total: 4000 },
      { id: "5", description: "Soporte post-migración (3 meses)", quantity: 3, unitPrice: 1000, total: 3000 },
    ],
  },
  {
    id: "2",
    clientId: "2",
    title: "Desarrollo Plataforma Web",
    description: "Desarrollo de plataforma web personalizada",
    value: 28000,
    status: "draft",
    priority: "medium",
    validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { id: "1", description: "Diseño UX/UI", quantity: 60, unitPrice: 100, total: 6000 },
      { id: "2", description: "Desarrollo Frontend", quantity: 120, unitPrice: 90, total: 10800 },
      { id: "3", description: "Desarrollo Backend", quantity: 100, unitPrice: 95, total: 9500 },
      { id: "4", description: "Testing y QA", quantity: 20, unitPrice: 85, total: 1700 },
    ],
  },
  {
    id: "3",
    clientId: "3",
    title: "Estrategia Marketing Digital 2025",
    description: "Plan integral de marketing digital para el año 2025",
    value: 62000,
    status: "accepted",
    priority: "high",
    validUntil: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    sentAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    viewedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { id: "1", description: "Auditoría digital", quantity: 1, unitPrice: 5000, total: 5000 },
      { id: "2", description: "Estrategia SEO (12 meses)", quantity: 12, unitPrice: 2000, total: 24000 },
      { id: "3", description: "Gestión redes sociales (12 meses)", quantity: 12, unitPrice: 1500, total: 18000 },
      { id: "4", description: "Campañas publicitarias", quantity: 1, unitPrice: 15000, total: 15000 },
    ],
  },
]

export const mockContracts: Contract[] = [
  {
    id: "1",
    clientId: "3",
    proposalId: "3",
    title: "Contrato Marketing Digital 2025",
    value: 62000,
    status: "active",
    startDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 360 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    signedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    terms: "Contrato anual renovable. Pagos mensuales. Incluye soporte y actualizaciones.",
  },
  {
    id: "2",
    clientId: "5",
    title: "Desarrollo E-commerce Internacional",
    value: 38000,
    status: "active",
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    signedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    terms: "Proyecto de 3 meses. Pago 50% inicio, 50% entrega final.",
  },
]
